import {expandedWorkflow} from './expanded-workflow.mjs';
import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1024,height:1366},isMobile:true,hasTouch:true});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.addInitScript(()=>localStorage.setItem('fichadrive-language','es'));await expandedWorkflow(page);await page.goto('http://localhost:8800');await page.getByRole('button',{name:'Crear mi primer alumno'}).click();await page.locator('[name=name]').fill('Alumno prueba');await page.getByRole('button',{name:'Crear alumno',exact:true}).click();
await page.locator('[data-rating="0:3"]').click();await page.locator('[data-rating="1:2"]').click();await page.reload();assert.equal(await page.locator('[data-rating="0:3"]').getAttribute('aria-pressed'),'true');await page.locator('[data-rating="0:3"]').click();assert.equal(await page.locator('[data-rating="0:3"]').getAttribute('aria-pressed'),'false');await page.getByRole('button',{name:'Deshacer',exact:true}).click();assert.equal(await page.locator('[data-rating="0:3"]').getAttribute('aria-pressed'),'true');
await page.locator('[data-tag="Buena actitud"]').click();await page.locator('[data-next="4"]').click();await page.getByRole('button',{name:'Finalizar clase'}).click();assert.equal(await page.locator('.history-item').count(),1);await page.getByRole('button',{name:'Revisar',exact:true}).click();await page.locator('[data-rating="2:1"]').click();await page.getByRole('button',{name:'Terminar revisión'}).click();await page.getByRole('button',{name:'Evolución',exact:true}).click();assert.equal(await page.locator('.chart-col').count(),1);
await page.getByRole('button',{name:'Informe / PDF'}).click();assert.equal(await page.locator('.report-table tbody tr').count(),9);const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Guardar PDF'}).click();const download=await downloadPromise;await fs.mkdir('test-results',{recursive:true});await download.saveAs('test-results/ficha.pdf');assert.ok((await fs.stat('test-results/ficha.pdf')).size>1000);
const backupPromise=page.waitForEvent('download');await page.locator('[data-action=backup]:visible').first().click();const backup=await backupPromise;await backup.saveAs('test-results/copia.json');const data=JSON.parse(await fs.readFile('test-results/copia.json'));assert.equal(data.students[0].sessions[0].ratings[2],1);
await page.locator('#import').setInputFiles('test-results/copia.json');await page.getByRole('button',{name:'Sustituir y recuperar'}).click();assert.equal(await page.locator('h1').innerText(),'Alumno prueba');
await page.evaluate(()=>navigator.serviceWorker.ready);await page.reload();await context.setOffline(true);await page.reload();await page.locator('[data-rating="3:2"]').click();await page.reload();assert.equal(await page.locator('[data-rating="3:2"]').getAttribute('aria-pressed'),'true');await context.setOffline(false);
for(const [width,height]of [[1024,1366],[768,1024],[390,844]]){await page.setViewportSize({width,height});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`Overflow at ${width}`);await page.screenshot({path:`test-results/ficha-${width}.png`,fullPage:true})}
assert.deepEqual(errors,[]);console.log('PASS: create, autosave, toggle, undo, finish, edit, progress, PDF, backup/restore, offline, tablet/mobile layout.');await browser.close();
